# ------------------------------------------------------------- #
# Note: this file is automatically managed in template-template #
# ------------------------------------------------------------- #

name: template-sync

on:
  pull_request:
  pull_request_target:
  push:
    branches: master

jobs:
  is-pull-or-push:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    # it listens to pull_request_target but only run on push, pull_request
    # it will only run for author's own PRs, otherwise, there is no github-token to use!
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)

    steps:
      - run: echo ::info ::this is a pull_request event

  template-sync:
    needs: is-pull-or-push

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-workflow-queue@v1.1

      - uses: actions/checkout@v2

      - uses: ahmadnassri/action-template-repository-sync@v1.6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
